on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GITLAB_THINKR_PAT: ${{ secrets.GITLAB_THINKR_PAT }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        run: |
          brew install pandoc

      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Install packages
        run: |
          Rscript -e 'install.packages("renv")'
          Rscript -e 'source("renv/activate.R")'
          Rscript -e 'install.packages("git2r")'
          Rscript -e 'tmpform <- tempfile(pattern = "form-");
            git2r::clone("https://git.thinkr.fr/ThinkR/formation", local_path = tmpform,
             credentials = git2r::cred_user_pass("gitlab-ci-token", Sys.getenv("GITLAB_THINKR_TOKEN")));
            remotes::install_local(path = tmpform, upgrade = FALSE)'
          Rscript -e 'options(renv.auth.formation = list(GIT_PAT = Sys.getenv("GITLAB_THINKR_PAT")));renv::restore()'
          # Rscript -e 'options(remotes.git_credentials = git2r::cred_user_pass("gitlab-ci-token", Sys.getenv("GITLAB_THINKR_PAT")));renv::restore()'

# Mettre les options pour avec renv, qui n'est pas pareil que remotes...

      - name: Render Rmarkdown files
        run: |
          Rscript -e 'source("compile_course.R")'

      # - name: Commit results
      #   run: |
      #     git config --local user.name "$GITHUB_ACTOR"
      #     git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
      #     git commit ${RMD_PATH[*]/.Rmd/.md} -m 'Re-build Rmarkdown files' || echo "No changes to commit"
      #     git push origin || echo "No changes to commit"
