on:
  push:
    branches:
      - main
      - master
      - the-ci
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GITLAB_THINKR_PAT: ${{ secrets.GITLAB_THINKR_PAT }}
      REPO_NAME: "https://packagemanager.rstudio.com/all/__linux__/focal/latest"
      FILL_HOME: "FALSE"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')

      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Install packages
        run: |
          source("renv/activate.R")
          install.packages("git2r")
          install.packages("remotes")
          options(renv.auth.formation = list(GIT_PAT = Sys.getenv("GITLAB_THINKR_PAT")))
          renv::restore()
          tmpform <- tempfile(pattern = "form-")
          git2r::clone("https://forge.thinkr.fr/thinkr/thinkrverse/formation/", local_path = tmpform,
             credentials = git2r::cred_user_pass("gitlab-ci-token", Sys.getenv("GITLAB_THINKR_PAT")))
          remotes::install_local(path = tmpform, upgrade = FALSE, force = TRUE)
          # Rscript -e 'options(remotes.git_credentials = git2r::cred_user_pass("gitlab-ci-token", Sys.getenv("GITLAB_THINKR_PAT")));renv::restore()'
        shell: Rscript {0}

# Mettre les options pour avec renv, qui n'est pas pareil que remotes...

      - name: Render Rmarkdown files
        run: |
          source("compile_course.R")
          dir.create("public")
          file.copy("les_cours/complet/support", "public", recursive = TRUE)
          writeLines("!*.html\n!*.pdf\n!*_files/", "public/support/.gitignore")
        shell: Rscript {0}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/support
          force_orphan: true
